@startuml
'https://plantuml.com/class-diagram

class Multa
class Servicio
class Sistema
class Técnico
class VideoDeSeguridad
class Login
class AlícuotaGUIAdministrador
class InstalaciónGUIAdministrador
class Login
class MenuPrincipalAdministrador
class MultaGUIAdministrador
class ServicioGUIAdministrador
class TécnicoGUIAdministrador
class AlícuotaGUIInquilino
class InstalaciónGUIInquilino
class MenuPrincipalInquilino
class MultaGUIInquilino
class VideoDeSeguridadGUIInquilino
@enduml